#!/usr/bin/env python3
"""Embed compiled overlay blobs (.dtbo) as C arrays for the loader module."""
import sys, struct
from pathlib import Path
if not __debug__: raise SystemExit('Refusing python -O: assert statements here are safety checks')

out = Path(sys.argv[1])
lines = ["/* Generated by mk-blob-header.py; do not edit. */", "#include <linux/types.h>", ""]
for spec in sys.argv[2:]:
    name, path = spec.split("=", 1)
    data = Path(path).read_bytes()
    magic, total = struct.unpack(">II", data[:8])
    assert magic == 0xd00dfeed and total == len(data), (path, hex(magic), total, len(data))
    lines.append(f"static const u8 {name}[] __aligned(8) = {{")
    for i in range(0, len(data), 16):
        lines.append("\t" + ", ".join(f"0x{b:02x}" for b in data[i:i + 16]) + ",")
    lines.append("};")
    lines.append(f"static const u32 {name}_size = {len(data)};")
    lines.append("")
out.write_text("\n".join(lines))
print(f"wrote {out} ({sum(1 for l in lines)} lines)")
